plugins { id 'com.android.application' }

android {
    namespace 'com.tbt2.chargestop'
    compileSdk 35
    defaultConfig {
        applicationId 'com.tbt2.chargestop'
        minSdk 26
        targetSdk 28
        versionCode 4
        versionName '0.4.0'
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
